---
title: "Owner Analysis"
format: html
author: Zephyr Girard
---

## Exercise: Explore, Clean and Wrangle Data

```{r}
#| warning: false
#| message: false
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

### Read in data

```{r}
#| message: false
#| warning: false
lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")
```

#### Explore data

```{r}
glimpse(lobster_abundance)
colnames(lobster_abundance)
head(lobster_abundance)
```

### Cleaning data

```{r}
unique(lobster_abundance$SIZE_MM)
# want to get rid of -99999 make na
lobster_abundance <- lobster_abundance %>% 
  mutate(SIZE_MM = na_if(SIZE_MM, -99999.0))
unique(lobster_abundance$SIZE_MM)

not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")

big_lob_aque <- lobster_abundance %>%
  filter(SITE == "AQUE") %>% 
  filter(SIZE_MM >= "70")
```

## Exercise: Data Visualization

```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

ggplot(lobsters_summarize, aes(x = YEAR, y = COUNT, color = SITE))+
  geom_point()

ggsave("../figs/zeph_count_year.png", plot = last_plot(), width = 6, height = 4, units = "in")

ggplot(lobsters_summarize, aes(x = YEAR, y = COUNT))+
  geom_line(aes(color = SITE))

ggsave("../figs/zephyr_line_count_year.png", width = 6, height = 4, units = "in")
```

```{r}
ggplot(lobster_abundance, aes(x = SIZE_MM))+
  geom_histogram()+
  facet_wrap("SITE")

ggsave("../figs/zeph_histogram.png", width = 6, height = 4, units = "in")
 
```

```{r}
#| warning: false
#| message: false
lobster_size_large <- lobster_abundance %>% 
  filter(YEAR %in% c(2019, 2020, 2021)) %>% 
  mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>% 
  group_by(SITE, SIZE_BIN) %>% 
  summarize(COUNT = n()) %>% 
  drop_na()
glimpse(lobster_size_large)

ggplot(lobster_size_large, aes(x = SITE, y = COUNT, fill = SIZE_BIN))+
  geom_col(position = "dodge")
ggsave("../figs/zeph_barplot.png", width = 6, height = 4, units = "in")
```

